info = {
    "Pronoun": "him",
    "Name": "Manav",
    "Full_Name": "Manav Garkel",
    "Intro": "A Software Engineer with a passion for backend development, data engineering, and ML/AI technologies - driven to build scalable, intelligent systems that solve real-world problems",
    "About": "Backend engineer focused on building scalable data systems, APIs, and automation workflows in Python."
    " Experienced with SQL and NoSQL databases, cloud-native infrastructure, and integrating LLMs into production systems.",
    "City": "Alexandria, Virginia",
    "Photo": "images/personal_photo.jpg",
    "Email": "manav.garkel@gmail.com",
    "LinkedIn": "https://www.linkedin.com/in/manav-garkel/",
}
work_experience = {
    1: {
        "job_title": "Sr Software Engineer",
        "company": "Freddie Mac",
        "start": "2021-05-01",
        "end": "2025-04-01",
        "bullets": [
            "Developing Mercury+, a Flask-based Python forecasting and analysis platform enabling Freddie Mac's finance division to forecast loans and securities performance under varying economic scenarios, improving risk and loss assessments, and significantly reducing manual reporting.",
            "Led a 12-month initiative for ERCF capital reporting reducing a 24–48 hour manual reporting process to 15 minutes, acting as both project manager and lead engineer— drove the project through development and user acceptance testing, conducting in-depth financial analysis to validate Mercury+ outputs against acceptance criteria while ensuring on-time production deployment.",
            "Leading development of an ETL feature that integrates forecasted loan and securities performance with capital calculations, enabling the company to project future capital requirements vastly improving and automating Freddie Mac's risk-assessment efforts.",
            "Developed a Python microservice with FastAPI to deliver streamlined, secure, and high-performance access to company data sources, implementing OAuth 2.0 authentication to prevent unauthorized access.",
        ],
        "className": "freddie",
        "logo_url": "https://media.licdn.com/dms/image/v2/D4E0BAQGzKBAwTUdgrw/company-logo_200_200/company-logo_200_200/0/1719929504536/freddie_mac_logo?e=1749686400&v=beta&t=HM12FwpIBpnYl20chy1oMq4hKCd7X3v_2UJUhgWmSN4",
    },
    2: {
        "job_title": "AI Software Engineer",
        "company": "Selling.com",
        "start": "2023-03-01",
        "end": "2024-03-01",
        "bullets": [
            "Engineered a new capability for a B2B sales platform to deliver daily ingested corporate news, enabling sales teams to personalize outreach.",
            "Designed and automated a web-scraping ETL pipeline to collect and process 10,000+ news articles per day.",
            "Integrated GPT-3.5/4-turbo for named entity recognition to extract company names and utilized few-shot prompting for multi-label classification of news articles across 21 categories.",
            "Architected and built a robust, scalable, cloud-native data pipeline using AWS DynamoDB, SQS, and S3 for high availability and performance.",
        ],
        "className": "selling",
        "logo_url": "https://media.licdn.com/dms/image/v2/D4E0BAQE71GztFp03VA/company-logo_200_200/company-logo_200_200/0/1705421353782/infotelligent_logo?e=1749686400&v=beta&t=DB2r3I9iXmyjcdHcz_3s1uvh9asmxTKVGS_4kPUO3lw",
    },
    3: {
        "job_title": "Software Engineering Intern",
        "company": "SyncLayer Inc.",
        "start": "2021-02-01",
        "end": "2021-09-01",
        "bullets": [
            "Developed features for a geospatial analytics web-application that ingests historical and live mobile tower data, enabling law enforcement agencies to track suspect movements and investigate crime scenes more efficiently.",
            "Enhanced the SMS orchestration service in Groovy using Twilio API to send users automated text messages based on user alerts and notification settings",
            "Implemented frontend (vanilla JS) and backend (Groovy) functionality in the web-application to provide users a new phone number lookup feature using Twilio API",
        ],
        "className": "synclayer",
        "logo_url": "https://www.synclayerinc.com/wp-content/uploads/2018/04/synclayer_logo.png",
    },
    4: {
        "job_title": "Graduate Teaching Asst",
        "company": "GMU",
        "start": "2020-08-01",
        "end": "2021-05-01",
        "bullets": [
            "Instructing lab coding sessions and holding weekly office hours for courses teaching OOP in python"
        ],
        "className": "gmu",
        "logo_url": "https://media.licdn.com/dms/image/v2/D4E0BAQHtmV4ZuBz4MQ/company-logo_200_200/company-logo_200_200/0/1715605771209/george_mason_university_college_of_engineering_and_computing_logo?e=1749686400&v=beta&t=VvKOqZs4sjngfjDL4vaTYvecWrVG85k9w5yB4Zf5sK0",
    },
    5: {
        "job_title": "Data Science & ML Intern",
        "company": "Selling.com",
        "start": "2020-05-01",
        "end": "2020-08-01",
        "bullets": [
            "Built TF-IDF + SVM-based classification models with 90%+ accuracy to categorize 13M job titles by level and department",
            "Developed NER-based scripts to extract CEO information for 1.2M companies via web mining",
        ],
        "className": "selling",
        "logo_url": "https://media.licdn.com/dms/image/v2/D4E0BAQE71GztFp03VA/company-logo_200_200/company-logo_200_200/0/1705421353782/infotelligent_logo?e=1749686400&v=beta&t=DB2r3I9iXmyjcdHcz_3s1uvh9asmxTKVGS_4kPUO3lw",
    },
    6: {
        "job_title": "QA Specialist II",
        "company": "Dexcom, Inc.",
        "start": "2017-02-01",
        "end": "2019-07-01",
        "bullets": [
            "Transitioned 95% of complaint code (including product and data investigations review) volume over to the Manila, Philippines office during a four-month assignment abroad",
            "Successfully trained 100+ employees and new hires for the Quality Assurance team in Manila, Philippines",
            "Deployed processes and procedures to ensure effective transition of workload and continued workflow between San Diego and Manila locations",
            "Led a process improvement project to identify sources of errors within product and data investigations, driving down error percentage from 12% to 5% in a duration of 10 months in conjunction with Field Failure Analysis Lab",
            "Identified a bug in the sensor algorithm in conjunction with R&D engineering team and implemented a fix to reduce sensor malfunctions by 1% (5000 sensors) each month",
            "Department liaison between Quality Assurance dept. and Field Failure Analysis Lab – worked with engineers in the lab to draft SOP’s and PI’s for failed product investigations and root cause analysis",
        ],
        "className": "dexcom",
        "logo_url": "https://media.licdn.com/dms/image/v2/C560BAQE3mpvPlafs2Q/company-logo_200_200/company-logo_200_200/0/1675797236800/dexcom_logo?e=1749686400&v=beta&t=-vrCuglmypNCIAojWf8VXOaJgHFGdNgCvD8bq2qMnXY",
    },
    7: {
        "job_title": "Research Associate",
        "company": "UC San Diego",
        "start": "2016-11-01",
        "end": "2017-06-01",
        "bullets": [
            "Developed C++ code for the lattice Monte Carlo simulation software to study the coarse-grained dynamics of nanoparticle diffusion and self – assembly in a polymer thin film. This study was critical in predicting and engineering electromechanical properties of advanced Nano – composite materials",
            "Designed and executed an experiment to characterize the higher order structures formed by Nano particle diffusion and self – assembly",
            "Implemented MATLAB scripts to visualize the morphology of the higher – order structures obtained from nanoparticle diffusion and self – assembly",
            "Automated the simulation process by developing a Python program to generate input files of varying initialization parameters. These files were used as input arguments for the Monte Carlo simulation software enabling the team to run multiple simulations at once while also generating an efficient output of organized data sets",
        ],
        "className": "ucsd",
        "logo_url": "https://media.licdn.com/dms/image/v2/C560BAQHQYa-3EY_aaQ/company-logo_200_200/company-logo_200_200/0/1630633790917/university_of_california_at_san_diego_logo?e=1749686400&v=beta&t=M9x4N2VgAkuaL0BlvuebhoHZO__Qn4zSqDINKOEsjno",
    },
    8: {
        "job_title": "Student Fundraiser",
        "company": "UC San Diego",
        "start": "2014-06-01",
        "end": "2015-04-01",
        "bullets": [
            "Reached out to alumni and friends of the University in order to raise fund for various Scholarships/Departments at UCSD",
            "Raised $18,000 during an 11-month span at the Telephone Outreach Program",
            "Achieved a participation (pledge) rate of 70%",
            "Awarded Top 5 Caller of the Month 8 out of 11 months in the program",
        ],
        "className": "ucsd",
        "logo_url": "https://media.licdn.com/dms/image/v2/C560BAQHQYa-3EY_aaQ/company-logo_200_200/company-logo_200_200/0/1630633790917/university_of_california_at_san_diego_logo?e=1749686400&v=beta&t=M9x4N2VgAkuaL0BlvuebhoHZO__Qn4zSqDINKOEsjno",
    },
    9: {
        "job_title": "Internship",
        "company": "Nielsen Company",
        "start": "2013-06-01",
        "end": "2013-08-01",
        "bullets": [
            "Successfully built Polygon 1.0, a database and reporting system, by collaborating data for 5000+ North American contractors",
            "Enabled efficient data analysis by consolidating data from various platforms including OLAP Cubes, SharePoint lists and Excel files into a single data repository in Microsoft Excel",
        ],
        "className": "nielsen",
        "logo_url": "https://media.licdn.com/dms/image/v2/C4E0BAQFKa_ObftR_8w/company-logo_200_200/company-logo_200_200/0/1634555714140/nielsen_logo?e=1749686400&v=beta&t=KrwvCxMUwQSPHRF471sWetxiKH2fUlGkV7GvhL2sEJY",
    },
    10: {
        "job_title": "Management Trainee",
        "company": "Nielsen Company",
        "start": "2011-07-01",
        "end": "2012-03-01",
        "bullets": [
            "Prepared monthly deliverables and invoices to be sent out to clients",
            "Assisted manager in client meetings",
            "Researched and acquired prospective clients to expand client base",
        ],
        "className": "nielsen",
        "logo_url": "https://media.licdn.com/dms/image/v2/C4E0BAQFKa_ObftR_8w/company-logo_200_200/company-logo_200_200/0/1634555714140/nielsen_logo?e=1749686400&v=beta&t=KrwvCxMUwQSPHRF471sWetxiKH2fUlGkV7GvhL2sEJY",
    },
}

hobbies = [
    (
        "🏋️‍♂️",
        "Weightlifting",
        "Building strength and discipline through consistent training.",
    ),
    ("🚶", "Daily Walks", "Time to decompress, reflect, and refresh."),
    (
        "🎸",
        "Learning Guitar",
        "Currently jamming through beginner songs and chords.",
    ),
    (
        "🏎️",
        "Formula 1",
        "Obsessed with strategy and the speed — race days are sacred.",
    ),
    ("⚽", "Soccer", "Die-hard Manchester United fan. GGMU ❤️"),
    (
        "✈️",
        "Travelling",
        "Always planning the next adventure to explore new cultures.",
    ),
    (
        "👨‍👩‍👧‍👦",
        "Friends & Family",
        "Making memories with the people who matter most.",
    ),
]
